:global:
  build:
    matrix:
      - GOOS: linux
        GOARCH: amd64
      - GOOS: darwin
        GOARCH: amd64
.travis.yml:
  sudo: true
  services:
    - docker
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST_TYPE: small
      - SNAP_VERSION: latest
        OS: alpine
        TEST_TYPE: large
      - SNAP_VERSION: latest_build
        OS: alpine
        TEST_TYPE: large
      - SNAP_VERSION: latest
        OS: xenial
        TEST_TYPE: large
      - SNAP_VERSION: latest
        OS: centos7
        TEST_TYPE: large
  matrix:
    exclude:
      - go: 1.6.3
        env: SNAP_VERSION=latest OS=alpine TEST_TYPE=large
      - go: 1.6.3
        env: SNAP_VERSION=latest_build OS=alpine TEST_TYPE=large
      - go: 1.6.3
        env: SNAP_VERSION=latest OS=xenial TEST_TYPE=large
      - go: 1.6.3
        env: SNAP_VERSION=latest OS=centos7 TEST_TYPE=large
