FROM intelsdi/snap:<%= ENV['SNAP_OS'] || "alpine" -%>_test

ENV CI_URL=https://s3-us-west-2.amazonaws.com/snap.ci.snap-telemetry.io

ADD ${CI_URL}/plugins/snap-plugin-collector-psutil/latest/linux/x86_64/snap-plugin-collector-psutil /opt/snap/plugins/snap-plugin-collector-psutil
ADD ${CI_URL}/snap/${SNAP_VERSION}/linux/x86_64/snap-plugin-collector-mock2 /opt/snap/plugins/snap-plugin-collector-mock2
COPY snap-plugin-publisher-file /opt/snap/plugins/snap-plugin-publisher-file
COPY tasks/ /opt/snap/tasks/

RUN chmod 755 /opt/snap/plugins/snap-plugin*
